# Generated by Django 4.0.4 on 2022-06-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paczka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descripton',
            new_name='description',
        ),
    ]
