# Generated by Django 4.0.4 on 2022-06-06 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paczka', '0002_rename_descripton_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
