# Generated by Django 4.0.4 on 2022-06-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczka', '0003_review_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(default='noemail@noemail.com', max_length=80),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phone',
            field=models.IntegerField(default='000000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='room',
            field=models.CharField(default='noroom', max_length=20),
            preserve_default=False,
        ),
    ]
