# Generated by Django 4.0.4 on 2022-06-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczka', '0004_lecturer_email_lecturer_phone_lecturer_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='phone',
            field=models.CharField(default='000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='room',
            field=models.CharField(default='noroom', max_length=20),
        ),
    ]
